### ISSUE TITLE
Autocomplete window does not appear in fullscreen applications

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1229]
> cannot work well in full screen iterm2

Waiting for more info. If this is happening to you, please let us know if you use any windowing tools (eg. magnet, amethyst) and any other relevant info. Multiple monitors? Quake mode?

**Comment by clstaudt** [comment]
I just installed fig and had a similar issue: The Fig overlays disappear once Terminal.app is in fullscreen mode. Unfortunately fullscreen is how I use the terminal every day.

**Comment by mschrage** [comment]
I have figured out what's going on here. If you've launched run `fig` and have this window open, the activation policy of the app changes. This prevents the autocomplete window from appearing over full-screen applications.

<img width="942" alt="Screen Shot 2022-03-31 at 1 03 10 PM" src="https://user-images.githubusercontent.com/3155109/161139903-e7d10296-1fdc-4466-8a31-d9940fbd7e13.png">

**Comment by stoopman** [comment]
When I use my terminal (in my case embedded terminal in Jetbrain phpstorm editor) in fullscreen, it the 'autocomplete' window does not show, when I quickly change spaces it see it popping up on the non full screen space :D

![Screenshot 2022-04-08 at 15 32 38 1](https://user-images.githubusercontent.com/5067761/162446443-6b2022dd-f09b-48f1-825d-02c56089a32e.png)

**Comment by mschrage** [comment]
Yeah, this is super reproducible. It is just tricky to resolve now that we want Fig to occasionally appear in the dock and behave like a normal application. This is a weird quirk of Apple's APIs.

**Comment by SeparateRecords** [comment]
It's worth noting that Raycast also has the same problem, if you open the raycast settings it no longer displays over fullscreen apps.

Is there a way to detect if the current app is fullscreened? Could possibly show it as a check in fig doctor, since as of right now this is the expected (although not desired) behavior

**Comment by mschrage** [comment]
As a workaround, I think I may close the Fig window if the user changes workspaces. Might be a little weird but still better than current behavior.

cc @SeparateRecords

**Comment by SeparateRecords** [comment]
That's a good solution I think. Realistically if the Fig window is open and they've changed workspaces, they've probably forgotten that it was even open anyway.

**Comment by mschrage** [comment]
This is fixed in the latest version of Fig! You can update by running `fig update` in your terminal :)

**Comment by nurielmeni** [comment]
For me Autocompletion still doesn't work on VSCODE terminal, when VSCODE in fullscreen mode. 
 - fig 2.7.5, 
 - OS: 13.0 (22A380)

**Comment by hanslemm** [comment]
> For me Autocompletion still doesn't work on VSCODE terminal, when VSCODE in fullscreen mode.
> 
> * fig 2.7.5,
> * OS: 13.0 (22A380)

Same problem for same config... the fig window is behind the VSCode in fullscreen... therefore you cannot see it!

**Comment by SeparateRecords** [comment]
Hmm... I can reproduce. Same setup too. Issue definitely not fully solved...

**Comment by SeparateRecords** [comment]
Actually, going to close this issue to keep count down. Will merge with #1964 🙂

**Comment by devidw** [comment]
Facing the described behavior on:

- fig_cli 2.14.0-beta.7
- macOS 13.2 (22D49)


https://user-images.githubusercontent.com/68775926/217642353-0856a46a-bdfd-403f-92ef-4737316ab095.mov
