### ISSUE TITLE
fig settings shows blank screen until manually selecting 'Settings' in the sidebar

### ISSUE THREAD

**Issue by endreymarcell** [withfig/fig#1537]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
When calling `fig settings`, only the sidebar loads, the actual settings screen stays blank (and the dropdown selector above it also has no value).
Settings only show up if I explicitly click Settings in the sidebar.
See screen recording: https://capture.dropbox.com/yCcLzkId1qyPP9Rr

This is happening consistently.

The debugger is not showing any issues:
![image](https://user-images.githubusercontent.com/9928328/173416439-341e8bdb-a57c-4694-b4c7-7fb74c71beb8.png)

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B453) [Beta] [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/sbin:/Users/marcell.endrey/n/bin:/Users/marca/n/bin:/Users/marcell.endrey/.fig/bin:/Users/marcell.endrey/.local/bin:/Users/marca/.fig/bin:/Users/marca/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro11,3
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 11.5.0 (20G71)
## Environment:
  - User Shell: /usr/local/bin/fish
  - Current Directory: /Users/marca
  - CLI Installed: true
  - Executable Location: /Users/marca/.fig/bin/fig
  - Current Window ID: 56208/% (com.apple.Terminal)
  - Active Process: fish (78561) - /dev/ttys002
  - Installed via Brew: true
  - Environment Variables:
    - FIG_TERM=1
    - PATH=/usr/local/sbin:/Users/marcell.endrey/n/bin:/Users/marca/n/bin:/Users/marcell.endrey/.fig/bin:/Users/marcell.endrey/.local/bin:/Users/marca/.fig/bin:/Users/marca/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    - TERM_SESSION_ID=EB394324-DBE2-432C-B290-D8449030B48C
    - FIG_INTEGRATION_VERSION=8
    - TERM=xterm-256color
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=78561
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```
```

**Comment by SeparateRecords** [comment]
This is easy to repro- thanks for the report @endreymarcell :)

For now, easy workaround is to just run `fig` instead.

**Comment by rahulsarathy** [comment]
This should be fixed now!

**Comment by richpoirier** [comment]
Still happening for me in 1.0.61. Running `fig`, same thing. Both settings and the dashboard are blank windows.

```
fig-details:
  - desktop-version: Version 1.0.61 (B528) [U.S.]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,3
  - chip-id: Apple M1 Pro
  - cores: 8 (6 performance and 2 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/rich
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/opt/dev/bin/user:.:/Users/rich/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin:/opt/homebrew/bin:/Users/rich/.fig/bin:/Users/rich/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: w0t0p0:A22C1EBA-1100-4A9E-AD4F-CE9D600CC62E
    - FIG_PID: 99625
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false
```

**Comment by SeparateRecords** [comment]
@richpoirier Just to check though, it shows the sidebar but not the content? Or is it totally blank?

**Comment by richpoirier** [comment]
@SeparateRecords Dashboard: 
![image](https://user-images.githubusercontent.com/9813/192841923-26572623-36a6-464e-ae9a-1437f46a2981.png)

Settings:

![image](https://user-images.githubusercontent.com/9813/192841979-1680cb62-eee8-4c9c-afbc-29a03622c3f8.png)

I must say, I also get a blank screen in iTerm lately until I open a new tab. Not sure if it's related.

**Comment by richpoirier** [comment]
I good ol' restart fixed it 🤷🏻

**Comment by theLomax** [comment]
I encountered this issue just after a system restart. `fig quit`, then `fig` resolved it. `fig restart` probably would have as well?
