### ISSUE TITLE
error: Could not sync remote dotfiles

### ISSUE THREAD

**Issue by snilli** [withfig/fig#1753]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

~/.zshrc
```
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && . "$HOME/.fig/shell/zshrc.pre.zsh"

eval "$(oh-my-posh --init --shell zsh --config $(brew --prefix oh-my-posh)/themes/montys.omp.json)"
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && . "$HOME/.fig/shell/zshrc.post.zsh"
```

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B518) [ABC]
hardware-info:
  - model: MacBook Air
  - model-id: MacBookAir10,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/admin
  - exe-path: /Users/admin/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /Users/admin/.nvm/versions/node/v16.17.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/admin/.fig/bin:/Users/admin/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: w0t8p0:FFA9C47C-575B-4E4D-94F8-0C3A97239C3B
    - FIG_PID: 20813
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mvgijssel** [comment]
Running into this _occasionally_ as well. Without having any more context, feels like a rate limiting / server performance issue, due to the on and off nature of the problem for me.

**Comment by mschrage** [comment]
Hey @mvgijssel @snilli thanks for reporting this. We've been investigating some backend performance issues and believe this should be resolved (or at least mitigated).

Can you run `FIG_LOG_LEVEL=trace fig source` and share the output here?

**Comment by mvgijssel** [comment]
@mschrage unable to reproduce, working as a charm now ❤️. 

```bash
❯ FIG_LOG_LEVEL=trace fig source


✅ Dotfiles sourced!


```

**Comment by mschrage** [comment]
@mvgijssel great to hear! I'll leave this issue open for confirmation from @snilli, but I think this likely has been resolved.

**Comment by snilli** [comment]
![image](https://user-images.githubusercontent.com/34303427/189270446-8c7fa7e2-b29b-4b07-9b2a-3615e934305b.png)
I find root caust. That don't find module in node_module

**Comment by mschrage** [comment]
It looks like you've managed to add a plugin that doesn't exist. 

Run the following command and this issue should be resolved:
`fig plugins remove oh-my-posh`

**Comment by AlwaysAwake** [comment]
@mschrage 
I'm still having this issue while setting up my new Mac.
It keeps finding the Oh My ZSH module even I already removed that all plugins

`% RUST_BACKTRACE=1 FIG_LOG_LEVEL=trace fig source`
error: 
   0: Could not sync remote dotfiles
   1: Unexpected Server Error: Cannot find module '/node_modules/@fig/plugins/dist/cjs/plugins/Oh My ZSH/index.js' imported from /node_modules/@fig/plugins/dist/cjs/util/index.js

Location:
   fig_cli/src/cli/source.rs:21

```rs
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 3 frames hidden ⋮                               
   4: fig_cli::cli::Cli::execute::{{closure}}::hf3575b1e1f06335b
      at <unknown source file>:<unknown line>
   5: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll::h6b0cf37cef8e15de
      at <unknown source file>:<unknown line>
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc0027f361110f5aa
      at <unknown source file>:<unknown line>
   7: tokio::runtime::context::budget::h13a5b1e110699932
      at <unknown source file>:<unknown line>
   8: tokio::runtime::park::CachedParkThread::block_on::h9ebfb7dd3ae2ec93
      at <unknown source file>:<unknown line>
   9: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h319e8cf24a2056d9
      at <unknown source file>:<unknown line>
  10: tokio::runtime::runtime::Runtime::block_on::h62164b8f7d1bd509
      at <unknown source file>:<unknown line>
  11: fig_cli::main::h3fe1489d1df38b1a
      at <unknown source file>:<unknown line>
  12: std::sys_common::backtrace::__rust_begin_short_backtrace::h93cf77c2b653667f
      at <unknown source file>:<unknown line>
  13: std::rt::lang_start::{{closure}}::hb3ab9df7b4e38373
      at <unknown source file>:<unknown line>
  14: std::rt::lang_start_internal::h94fa211da9d06d56
      at <unknown source file>:<unknown line>
  15: _main<unknown>
      at <unknown source file>:<unknown line>
```

**Comment by andriilive** [comment]
I'm getting a Reqwest error for some reason

```
error:
   0: Could not sync remote dotfiles
   1: Reqwest error: error sending request for url (https://api.fig.io/dotfiles/source/all?os=macos&architecture=aarch64&device=476622b2de9a76bc76ab78eb616aed0f7329bf55219102dbafc0fe97f08b30b6&pluginsDirectory=%2FUsers%2Fandy%2F.local%2Fshare%2Ffig%2Fplugins&macosVersion=13.3.1): error trying to connect: tls handshake eof

Location:
   fig_cli/src/cli/source.rs:21

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
