### ISSUE TITLE
No plugins are actually being applied, even after update and reinstall

### ISSUE THREAD

**Issue by jonas-zebari** [withfig/fig#1800]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

I had been using ohmyzsh and zsh-syntax-highlighting for a few weeks (via the plugins store) and was really loving it. However, one day about 2 weeks ago, all my plugins stopped working. They don't break or anything, they just are not present whatsoever. I've tried updating fig, fig source, fig doctor, fig restart, uninstalling and reinstalling all my plugins, uninstalling and reinstalling fig itself, and nothing has made a difference. Would appreciate any insight here. Thanks!

https://user-images.githubusercontent.com/38041304/191039352-1c2de34d-bd66-4c0b-976b-520f7001e50e.mov

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B526) [U.S.]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro15,2
  - chip-id: 
  - cores: 4
  - mem: 16 GB
os-info:
  - macOS 12.5.0 (21G72)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/jonaszebari/Documents/dev/Kumanu-Mobile
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /Users/jonaszebari/.rvm/gems/ruby-2.6.5/bin:/Users/jonaszebari/.rvm/gems/ruby-2.6.5@global/bin:/Users/jonaszebari/.rvm/rubies/ruby-2.6.5/bin:/Users/jonaszebari/.nvm/versions/node/v12.22.10/bin:/usr/local/opt/ruby/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/jonaszebari/.fig/bin:/Users/jonaszebari/.local/bin:/usr/local/bin:/Users/jonaszebari/fvm/default/bin:/Users/jonaszebari/.rvm/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 0F790E5E-EAF3-40B9-A307-B3C673D95DBB
    - FIG_PID: 79069
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by jonas-zebari** [comment]
`fig doctor` returns with "Everything looks good"

**Comment by mschrage** [comment]
Hey @jonas-zebari! Our syncing infra was being flaking and this prevented changes from being applied at the appropriate time.

This should be resolved now!

**Comment by jonas-zebari** [comment]
@mschrage I don't think this is fixed. I checked for updates and re-attempted fig source, restart, restarting my terminal, etc. and none of the plugins are present.

**Comment by jonas-zebari** [comment]
@mschrage Pinging you again because this is not fixed for either of my computers. My issues are still as described in the original post.

**Comment by jonas-zebari** [comment]
@mschrage @chaynabors I'm wondering if there's anything I can do to help someone look into this?

**Comment by mschrage** [comment]
What happens when you run `fig source`?

**Comment by jonas-zebari** [comment]
I get an output saying "Dotfiles sourced!" and then it spits out all my aliases

**Comment by SeparateRecords** [comment]
Super strange @jonas-zebari. Can you pick a time on my calendar? We'll do a 1:1 debugging call to figure out what's happening 🙂 https://calendly.com/robert-fig/support

**Comment by jonas-zebari** [comment]
@SeparateRecords So, I decided to mess around with some of the aliases I have saved to see if the issue could be with one of this. It turns out one of my aliases seems to have broken `fig source` somehow. When I removed this alias, everything went back to normal: 

Alias: `;`
Value: ` && `
