### ISSUE TITLE
bug: fig doesnt work on two screens

### ISSUE THREAD

**Issue by stefanmatar** [withfig/fig#1951]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

Autocompletions happen on main screen only

### Actual behaviour

Autocompletions are shown only on the main macos screen.

### Steps to reproduce

Open terminal
Move it to second screen
Autocomplete via "cd "

### Environment

```yaml
fig-details:
  - desktop-version: 
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,3
  - chip-id: Apple M1 Pro
  - cores: 10 (8 performance and 2 efficiency)
  - mem: 32 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by mschrage** [comment]
Hey @stefanmatar! Thanks for letting us know. We are investigating. Can you share the layout of your monitors (go to System Preferences > Displays)?

**Comment by deboradurek** [comment]
Hey @mschrage! I'm having the same issue as @stefanmatar. If I can collaborate, here is the layout of my monitors.

<img width="349" alt="Screen Shot 2022-10-27 at 5 38 25 PM" src="https://user-images.githubusercontent.com/55608100/198417705-9a5823cd-4534-4ef3-80c7-5edbab91a766.png">

The autocomplete option box gets lost in between monitors (top and main bottom). I only see the end of the box, but none of the options is actually visible.
Thank you!

**Comment by mschrage** [comment]
Thank you @deboradurek! Can you run `fig diagnostic` and share the output here?

**Comment by deboradurek** [comment]
Sure, there you go:

```
❯ fig diagnostic

fig-details:
  - desktop-version: 
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,3
  - chip-id: Apple M1 Pro
  - cores: 10 (8 performance and 2 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/debora.durek/Desktop/Projects/Courier/react_courier
  - exe-path: /Users/debora.durek/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 8fe8337c-69cd-48c5-b2b3-718bcc99f679
    - FIG_HOSTNAME: L3620R9YCQ
    - FIG_TERM: 2.7.0-beta.1
    - PATH: /Users/debora.durek/.nvm/versions/node/v14.15.0/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Users/debora.durek/.fig/bin:/Users/debora.durek/.local/bin:/Users/debora.durek/Library/Android/sdk/emulator:/Users/debora.durek/Library/Android/sdk/platform-tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 94826
    - FIG_PARENT: 8fe8337c-69cd-48c5-b2b3-718bcc99f679
    - FIG_SET_PARENT: 8fe8337c-69cd-48c5-b2b3-718bcc99f679
```

**Comment by grant0417** [comment]
This should be fixed on the next beta going live in the next ~30 min, let us know if you run into any other issues!

**Comment by deboradurek** [comment]
Hello @grant0417, I'm still experiencing the same issue even after the update - using Version (2.7.0-beta.2).
Please, let me know if you need any other information that could help. Thank you!

**Comment by grant0417** [comment]
Hmm, @mschrage any idea why this is still not working?

**Comment by anthonychitez** [comment]
I'm experiencing the same issue. MacOS using vscode terminal the suggested options are being shown on my other monitor in the top left corner. Layout is my laptop monitor is the bottom screen and my external monitor is the upper screen. Fig Version 2.7.2

**Comment by DecadentIpsum** [comment]
I am facing the same issue

**Comment by mschrage** [comment]
Thanks for reporting @anthonychitez @DecadentIpsum! We are investigating cc: @chaynabors

**Comment by chaynabors** [comment]
Is this still an issue on 2.7.3-beta.0?

**Comment by mschrage** [comment]
@anthonychitez @DecadentIpsum @stefanmatar -- this should be fixed for _real_ on the latest version of Fig.

**Comment by grant0417** [comment]
The latest version 2.7.4

**Comment by DecadentIpsum** [comment]
> @anthonychitez @DecadentIpsum @stefanmatar -- this should be fixed for _real_ on the latest version of Fig.

Great work! Everything seems to work fine on version 2.7.4 🤝

**Comment by mschrage** [comment]
Amazing! I'm going to close this now, but please let us know if you run into other bugs.

And shoutout to @grant0417 and @chaynabors for debugging some very hairy window positioning logic.
