### ISSUE TITLE
Fig doctor reports Fig Integration: This terminal is not running with the latest Fig integration, please restart your terminal  FIG_TERM=2.7.0-beta.2

### ISSUE THREAD

**Issue by PJC-64** [withfig/fig#1968]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C5033e)

### Expected behaviour

fig doctor to report all OK

### Actual behaviour

Fig doctor reports Fig Integration: This terminal is not running with the latest Fig integration, please restart your terminal  FIG_TERM=2.7.0-beta.2

### Steps to reproduce

Open iTerm2, run fig doctor (as normal) to check all is OK.

### Environment

```yaml
fig-details:
  - 2.7.1-beta.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.1.0 (22C5033e)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.5.1/bin/fish
  - terminal: iterm
  - cwd: /Users/pjc
  - exe-path: /Users/pjc/.local/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /opt/homebrew/bin/fish
    - DISPLAY: /private/tmp/com.apple.launchd.8vMHkiEdFk/org.xquartz:0
    - PATH: /Users/pjc/perl5/bin:/opt/homebrew/lib/ruby/gems/3.0.0/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/sbin:/opt/homebrew/bin:/Users/pjc/.cargo/bin:/Users/pjc/.local/bin:/Users/pjc/.fig/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin
    - TERM: xterm-256color
    - FIG_PARENT: 
    - FIG_TERM: 2.7.0-beta.2
    - FIGTERM_SESSION_ID: 94be3dae-724a-46a0-8b31-a665f4fb37e1
    - FIG_PID: 33367
    - FIG_HOSTNAME: athena.local
    - FIG_SET_PARENT: w0t0p0:3B53ABF3-114B-493B-9AF7-049E76367BFB
```

**Comment by mschrage** [comment]
@PJC-64 did restarting your terminal resolve this warning?

**Comment by mschrage** [comment]
Investigated this a bit further and it should be resolved in the next update!

**Comment by PJC-64** [comment]
On November 1, 2022, Tommy Zarick ***@***.***> wrote:
> @PJC-64 <https://github.com/PJC-64> did restarting your terminal
> resolve this warning?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/withfig/fig/issues/1968#issuecomment-1298991001>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ANDZCUWF4IRXAEVGRL6G6KDWGFTS5ANCNFSM6AAAAAART5LV74>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by PJC-64** [comment]
Thamks - meant to say that restarting didn’t fix, but hit send
mistakenly!

On November 1, 2022, Tommy Zarick ***@***.***> wrote:
> Investigated this a bit further and it should be resolved in the next
> update!
>

—
Reply to this email directly, view it on GitHub
<https://github.com/withfig/fig/issues/1968#issuecomment-1299091963>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ANDZCURSORL27XSFG3IOCIDWGF3WBANCNFSM6AAAAAART5LV74>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by mschrage** [comment]
This should be resolved now!
