### ISSUE TITLE
bug: error fetching git repo in VSCode with Fig FIGTERM_SESSION_ID has no value

### ISSUE THREAD

**Issue by bmeverett** [withfig/fig#2030]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

Fig does not interfear with VSCode usage

### Actual behaviour

I am not able to use the built in VSCode Git integration to pull/push repositories. 

### Steps to reproduce

1. Use VSCode
2. Commit changes
3. Click one of these two buttons
![Image 2022-11-10 at 15 19 47](https://user-images.githubusercontent.com/3941006/201197637-ef20b7ab-db39-4cc6-a145-14f1075d54d2.png)
![Image 2022-11-10 at 15 19 50](https://user-images.githubusercontent.com/3941006/201197652-2565d1ec-09fd-4e46-befe-a87c166cc274.png)
4. Get error
```
vdollar_percent_expand: env var ${FIGTERM_SESSION_ID} has no value
/Users/brandon.everett/.fig/ssh line 2: Bad forwarding specification.
/Users/brandon.everett/.fig/ssh: terminating, 1 bad configuration options
fatal: Could not read from remote repository.
```

### Environment

```yaml
fig-details:
  - 2.7.7
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 32.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: vscode
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - FIG_TERM: 2.7.7
    - FIG_PARENT: a5b6c230-5ee9-4768-9372-311aa60e698e
    - TERM: xterm-256color
    - PATH: /Users/brandon.everett/.bun/bin:/Users/brandon.everett/.gem/ruby/2.6.0/bin:/Users/brandon.everett/.nvm/versions/node/v16.13.2/bin:/Users/brandon.everett/google-cloud-sdk/bin:/Users/brandon.everett/go/bin:/usr/local/bin:/Users/brandon.everett/.symfony/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/brandon.everett/.bun/bin:/Users/brandon.everett/.gem/ruby/2.6.0/bin:/Users/brandon.everett/.nvm/versions/node/v16.13.2/bin:/Users/brandon.everett/google-cloud-sdk/bin:/Users/brandon.everett/go/bin:/Users/brandon.everett/.symfony/bin:/Users/brandon.everett/.fig/bin:/Users/brandon.everett/.local/bin:/Users/brandon.everett/n/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
    - FIG_SET_PARENT: a5b6c230-5ee9-4768-9372-311aa60e698e
    - FIGTERM_SESSION_ID: a5b6c230-5ee9-4768-9372-311aa60e698e
    - SHELL: /bin/zsh
    - FIG_PID: 4046
    - FIG_HOSTNAME: C02FH6V6MD6R.local
```

Possible related to #1999

**Comment by grant0417** [comment]
Hey @bmeverett, try running `fig integrations install ssh` again, we just updated it so this issue should be resolved, otherwise @squili can help if this keeps happening!

**Comment by bmeverett** [comment]
I don't remember installing the ssh integration, but I tried the command you suggested, and still doesn't seem to work. I restarted fig and VSCode and still the same error.

**Comment by squili** [comment]
If you aren't using the ssh integrations, you can run `fig integrations uninstall ssh` to get rid of it. But if you want to keep it, could you run `cat ~/.fig/ssh` and let me know what it says?

**Comment by bmeverett** [comment]
Thanks, I installed and uninstalled the command and that fixed it.
