### ISSUE TITLE
Webstorm + Ventura: not working

### ISSUE THREAD

**Issue by koppieesq** [withfig/fig#2048]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

Fig should work in Webstorm on MacOS

### Actual behaviour

Fig autocomplete doesn't work!  😭 

### Steps to reproduce

1. Install Fig from website
2. Switch to beta track
3. Update to latest version
4. From command line: `fig integrations reinstall intellij`
5. Restart Webstorm, restart computer

### Environment

```yaml
fig-details:
  - 2.7.8
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: WebStorm
  - cwd: /Users/jordan.koplowicz
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 487bf491-70be-45a6-84f8-4e5e99c94f2f
    - FIG_HOSTNAME: jordan.koplowicz-3Q4M
    - FIG_TERM: 2.7.8
    - PATH: /Users/jordan.koplowicz/sonar-scanner/bin:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/jordan.koplowicz/.nvm/versions/node/v16.16.0/bin:/Users/jordan.koplowicz/.platformsh/bin:/Users/jordan.koplowicz/.composer/vendor/drush/drush/drush:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/munki:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jordan.koplowicz/.fig/bin:/Users/jordan.koplowicz/.local/bin:/Users/jordan.koplowicz/Library/Application Support/JetBrains/Toolbox/scripts:/Users/jordan.koplowicz/.composer/vendor/bin:/Users/jordan.koplowicz/PhpstormProjects/go :/Users/jordan.koplowicz/PhpstormProjects/go/bin 
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 3142
    - FIG_PARENT: 487bf491-70be-45a6-84f8-4e5e99c94f2f
    - FIG_SET_PARENT: 487bf491-70be-45a6-84f8-4e5e99c94f2f
```

**Comment by grant0417** [comment]
Hey @koppieesq, did you get any errors when running `fig integrations install intellij`?

Also is the window showing and not following the cursor or is it not showing at all?

**Comment by grant0417** [comment]
Could you also try running `fig integrations install input-method`

**Comment by koppieesq** [comment]
> Hey @koppieesq, did you get any errors when running `fig integrations install intellij`?
> 
> Also is the window showing and not following the cursor or is it not showing at all?

> Could you also try running fig integrations install input-method

Both commands succeed, but the popup window is not showing at all.

![image](https://user-images.githubusercontent.com/5446321/202004763-9f8eb658-03f4-4856-9a6a-01e250b1f073.png)

When I run `fig integrations install input-method`, it opens my preferences window and asks me to approve an input method:

![image](https://user-images.githubusercontent.com/5446321/202003554-86a4331e-398d-49fa-99d5-1416cee13049.png)

I click "ok", but it doesn't make a difference, even when I restart Webstorm.

**Comment by bognarlaszlo** [comment]
Hi @grant0417,

For me fig autocompletion is working with the `input-method ` integration, however I was not able to successfully install the `intellij` integration and (I think) because of this fig plugins (eg: oh-my-zsh) are not loaded.

I'm not sure if this should be a separate issue but it I'm almost sure it's related.

Thanks

**Comment by felix-berlin** [comment]
Looks like i have the very same issue like @koppieesq . I'm using Ventura (13.0.1) + PHP Storm.

**Comment by squili** [comment]
We don't support IntelliJ IDEs installed through Toolbox on MacOS!

**Comment by grant0417** [comment]
This should be resolved now in Fig 2.10, let me know if you continue to have any issues!

**Comment by OnyekaIjeh** [comment]
Still doesn't work on Ventura with fig 2.10
This is the `fig doctor --verbose` output
```
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ ~/.bashrc contains valid fig hooks
✔ ~/.profile contains valid fig hooks
✔ ~/.zshrc contains valid fig hooks
✔ ~/.zprofile contains valid fig hooks

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration
✔ SSH integration

Let's make sure Fig is running...
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
✔ OS is supported
✔ Fish is up to date
✔ Jetbrains Toolbox Check

Let's check fig diagnostic...
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled

Let's check your terminal integrations...
✔ Terminal support
✘ Input Method: Input Method is not installed
  Run `fig integrations install input-method` to enable it
  
   0: IO Error: No such file or directory (os error 2)
   1: No such file or directory (os error 2)

Location:
   /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/convert/mod.rs:552

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.


  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

```

**Comment by grant0417** [comment]
Can you run `fig integrations install input-method`

**Comment by OnyekaIjeh** [comment]
> Can you run `fig integrations install input-method`

I get this
```
error: IO Error: No such file or directory (os error 2)
```

**Comment by grant0417** [comment]
Can you run `FIG_LOG_LEVEL=debug fig integrations install input-method`

**Comment by OnyekaIjeh** [comment]
> Can you run `FIG_LOG_LEVEL=debug fig integrations install input-method`

```
error: 
   0: IO Error: No such file or directory (os error 2)
   1: No such file or directory (os error 2)

Location:
   fig_cli/src/cli/integrations.rs:172

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by jon-frankel** [comment]
I'm having this issue also, with RubyMine. I just updated fig and did all of the steps ask above. I recently updated my Mac to Ventura, but it started before the update, a few months ago. After updating the Mac, RubyMine, and fig, I finally start to file an issue and found this.

### Operating System
```
macOS 13.1.0 (22C65)
```

### Environment
```
fig-details:
  - 2.10.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: intellij-rubymine
  - cwd: /Users/jonathanfrankel/dev/hive-router
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 97418786-f4b0-455e-b6d5-4feb757c0449
    - FIG_HOSTNAME: Jonathans-Dutchie-Macbook.local
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.10.1
    - PATH: /Users/jonathanfrankel/.rvm/gems/ruby-3.0.0@global/bin:/Users/jonathanfrankel/.rvm/rubies/ruby-3.0.0/bin:/Users/jonathanfrankel/.rvm/bin:/Users/jonathanfrankel/.pyenv/shims:/Users/jonathanfrankel/Library/pnpm:/Users/jonathanfrankel/.yarn/bin:/Users/jonathanfrankel/.config/yarn/global/node_modules/.bin:/Users/jonathanfrankel/.nvm/versions/node/v16.14.0/bin:/Users/jonathanfrankel/dev/poc/kind-local:/Users/jonathanfrankel/.pyenv/bin:/Users/jonathanfrankel/.bin:/Users/jonathanfrankel/.path:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/jonathanfrankel/.cargo/bin:/Users/jonathanfrankel/dev/hive-router/node_modules/.bin:/Users/jonathanfrankel/.fig/bin:/Users/jonathanfrankel/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.rubymine
    - FIG_PID: 18306
    - FIG_SET_PARENT: 97418786-f4b0-455e-b6d5-4feb757c0449
```
### Reinstalling jetbrains
```
-> % FIG_LOG_LEVEL=debug FIG_LOG_STDOUT=true RUST_BACKTRACE=1 fig integrations install jetbrains
2022-12-18T04:43:26.164067Z DEBUG fig_cli::cli: 284: Command ran: ["fig", "integrations", "install", "jetbrains"]
error: 
   0: application folder does not exist

Location:
   fig_cli/src/cli/integrations.rs:201

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 3 frames hidden ⋮                               
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7e7dc5c1b4118fec
      at <unknown source file>:<unknown line>
   5: fig_cli::cli::Cli::execute::{{closure}}::h55d453cf4743f347
      at <unknown source file>:<unknown line>
   6: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll::h86e8c19a3a3a5935
      at <unknown source file>:<unknown line>
   7: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::hb2de1f4c597d4249
      at <unknown source file>:<unknown line>
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h49aa7ada3211842a
      at <unknown source file>:<unknown line>
   9: tokio::runtime::context::budget::hc404185a4d4cee90
      at <unknown source file>:<unknown line>
  10: tokio::runtime::park::CachedParkThread::block_on::hec9f0894ff6de72c
      at <unknown source file>:<unknown line>
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hccb7b569e7e639ea
      at <unknown source file>:<unknown line>
  12: fig_cli::main::h42597d7cb78ca1db
      at <unknown source file>:<unknown line>
  13: std::sys_common::backtrace::__rust_begin_short_backtrace::hf29ed8b650a21d2b
      at <unknown source file>:<unknown line>
  14: std::rt::lang_start::{{closure}}::hdb1adc6a6e3ad1a6
      at <unknown source file>:<unknown line>
  15: std::rt::lang_start_internal::h94fa211da9d06d56
      at <unknown source file>:<unknown line>
  16: _main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
```
### Reinstalling `input-method`
```
-> % FIG_LOG_LEVEL=debug FIG_LOG_STDOUT=true RUST_BACKTRACE=1 fig integrations install input-method
2022-12-18T04:51:19.725694Z DEBUG fig_cli::cli: 284: Command ran: ["fig", "integrations", "install", "input-method"]
2022-12-18T04:51:19.725967Z DEBUG fig_integrations::input_method: 292: Registering input source...
2022-12-18T04:51:19.792451Z DEBUG fig_integrations::input_method: 506: Launch Input Method...
2022-12-18T04:51:19.793835Z DEBUG fig_integrations::input_method: 216: enable input source.
2022-12-18T04:51:19.873792Z  INFO fig_integrations::input_method: 536: Input method installed successfully!
Installed!
You must restart your terminal to finish installing the input method.
```
No change after restarting RubyMine.

**Comment by koppieesq** [comment]
Good news: I can confirm Fig works again on my machine:

- Apple Silicon
- Ventura 13.1
- Webstorm installed via JetBrains Toolbox
- Fig v. 2.10.1 beta
