### ISSUE TITLE
Plugin error popup in JetBrains IDE (RubyMine)

### ISSUE THREAD

**Issue by chao-xian** [withfig/fig#2052]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

For the integration to work for JetBrains and see the option in Fig GUI.

### Actual behaviour

Every startup of RubyMine shows a popup mentioning an error but no detail.

<img width="377" alt="Screenshot 2022-11-10 at 12 40 54" src="https://user-images.githubusercontent.com/424772/201884168-14860311-913b-43b0-b596-bf41307a7c98.png">

I also go to look for the integration in the GUI but it doesn't show, though from documentation I think it's supposed to?

<img width="1142" alt="Screenshot 2022-11-15 at 09 34 30" src="https://user-images.githubusercontent.com/424772/201884274-781f08d9-418c-4fcf-a3e4-f50fb005d4c5.png">

I have given Fig input permissions several times too.

### Environment

```yaml
fig-details:
  - 2.7.8
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/kelvin.gan
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 6a4e1466-9c93-42d0-8b5d-815711cd2e21
    - FIG_HOSTNAME: GDS12901
    - FIG_TERM: 2.7.8
    - PATH: /Users/kelvin.gan/.nvm/versions/node/v19.0.0/bin:/Users/kelvin.gan/.rbenv/shims:/opt/homebrew/opt/libpq/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/sbin:/Users/kelvin.gan/.fig/bin:/Users/kelvin.gan/.local/bin:/Users/kelvin.gan/.local/bin:/Users/kelvin.gan/govuk/govuk-docker/exe
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 2312
    - FIG_PARENT: 6a4e1466-9c93-42d0-8b5d-815711cd2e21
    - FIG_SET_PARENT: 6a4e1466-9c93-42d0-8b5d-815711cd2e21
```

**Comment by chao-xian** [comment]
Forgot to add this is RubyMine version 2022.2.2

**Comment by grant0417** [comment]
This should be resolved now in Fig 2.10, let me know if you continue to have any issues!

**Comment by chao-xian** [comment]
Hi sorry I didn't see this update for a while over the hols. I'm afraid it's still happening for me on fig v 2.10.1 and RubyMine 2022.3.1
