### ISSUE TITLE
Autocomplete renders in the wrong place

### ISSUE THREAD

**Issue by admapop** [withfig/fig#2058]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.3.1 (21E258)

### Expected behaviour

When the autocomplete window appears it should be next to what I am typing

### Actual behaviour

When the autocomplete window appears it is in a completely different place. Could be on the same screen but far away from where I'm typing, same screen but completely random or even on a completely different screen.

Where I'm typing
![image](https://user-images.githubusercontent.com/52109936/202141234-ce80f871-9804-4211-8c4b-dac512940a52.png)

Where it's showing, completely random on a different screen.
<img width="687" alt="image" src="https://user-images.githubusercontent.com/52109936/202141389-38cde0d7-0c70-49c3-8e3e-081ae9e8b557.png">

### Steps to reproduce

Start up IntelliJ IDEA, open a terminal and start typing.

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 12.3.1 (21E258)
environment:
  - shell: /bin/zsh
  - terminal: intellij
  - cwd: 
  - exe-path: /Users/admapop/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: b85e4d02-3d2f-4475-862b-979d20b13b79
    - FIG_HOSTNAME: Adrians-MacBook-Pro.local
    - FIG_TERM: 2.7.9
    - PATH: 
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 99906
    - FIG_PARENT: b85e4d02-3d2f-4475-862b-979d20b13b79
    - FIG_SET_PARENT: b85e4d02-3d2f-4475-862b-979d20b13b79
```

**Comment by mschrage** [comment]
Hey @admapop, how did you install the JetBrains IDE you are using? This could be related to #2018.

**Comment by admapop** [comment]
Hey @mschrage I installed it via its own .dmg file, didn't use any Toolbox or installer.

One thing I can add is that it happens more often if I switch between fullscreen mode and windowed mode. 
Wildshot but I'm using [magnet](https://magnet.crowdcafe.com/) for window management.

**Comment by richardcase** [comment]
I am encountering this when using Kitty.

**Comment by JasonTheAdams** [comment]
I've also started having this issue on MacOS since the latest update. I have PhpStorm running on one monitor, and when I type in the terminal on that screen the Fig pop _sometimes_ displays in the bottom-left corner of my main monitor.

**Comment by JasonTheAdams** [comment]
To be clear, for me this is an intermittent issue. I just opened PhpStorm back up and the popup is in the correct place. I didn't update anything. I just opened it back up for work today; it wasn't working yesterday, it is today. Gotta love these kinds of bugs. 😅

**Comment by onkr0d** [comment]
Having the same issue with fig 2.9.0, macOS 13.0.1 (22A400). Started happening after I installed [Rectangle](https://rectangleapp.com/), which is similar to @admapop's [Magnet](https://magnet.crowdcafe.com/). 

Specifically, it happens only on my secondary monitor, not the main (laptop) one. Intellij installed from Toolbox, but that hasn't been an issue for me previously.

**Comment by tomhendra** [comment]
👋 Another Kitty user here experiencing the same issue.

**Comment by squili** [comment]
I'm no longer working at Fig, maybe @grant0417 can take a look

**Comment by grant0417** [comment]
This should be resolved now in Fig 2.10, let me know if you continue to have any issues!

**Comment by onkr0d** [comment]
Nope, the issue still persists. It is probably related to #2109.

**Comment by grant0417** [comment]
Can you make sure to restart both Fig and intellij

**Comment by tomhendra** [comment]
The issue persists with Fig v2.10.1 when using Kitty, after restarting both Fig and Kitty. 

![Demonstration of Fig error](https://res.cloudinary.com/tomhendra/video/upload/v1671095173/oddments/Screen_Recording_2022-12-15_at_10.01.41.mov)

**Comment by tomhendra** [comment]
The issue persists with Fig v2.10.1 when using Kitty, after restarting both. 


https://user-images.githubusercontent.com/32566274/207819098-44afff19-1229-4ed1-8a5b-ee05fca3024c.mov

**Comment by richardcase** [comment]
> This should be resolved now in Fig 2.10, let me know if you continue to have any issues!

I'm still getting this issue with kitty with 2.10.1

**Comment by grant0417** [comment]
Did not realize this was an issue on Kitty, thought it was only Jetbrains.

If you are having this issue with Kitty can you share the output of the following:

- `kitty --version` 
- `echo $__CFBundleIdentifier`
- `fig debug input-method`
- `fig

**Comment by tomhendra** [comment]
> 

```bash
~ 
❯ kitty --version           
kitty 0.26.5 created by Kovid Goyal
~ 
❯ echo $__CFBundleIdentifier
net.kovidgoyal.kitty
~ 
❯ fig debug input-method
Installed? true
TISInputSource {
    bundle_id: Some(
        "io.fig.cursor",
    ),
    input_source_id: Some(
        "io.fig.cursor",
    ),
    input_source_category: Some(
        "TISCategoryPaletteInputSource",
    ),
    input_source_is_enabled: Some(
        true,
    ),
    input_source_is_selected: Some(
        true,
    ),
    localized_name: Some(
        "FigInputMethod",
    ),
    input_mode_id: None,
    category_keyboard: None,
}
~ 
```

**Comment by grant0417** [comment]
Hey @tomhendra can you also run `fig doctor --verbose`

**Comment by tomhendra** [comment]
> Hey @tomhendra can you also run `fig doctor --verbose`

Sure can, Grant. Here you go. 

Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ ~/.bashrc contains valid fig hooks
✔ ~/.profile contains valid fig hooks
✔ ~/.zshrc contains valid fig hooks
✔ ~/.zprofile contains valid fig hooks

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration
✔ SSH integration

Let's make sure Fig is running...
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✘ Daemon diagnostics: Daemon websocket error
  Fig error: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /authenticate/ticket</pre>
</body>
</html>
 (status: 404 Not Found)

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
✔ OS is supported
✔ Fish is up to date
✔ Jetbrains Toolbox Check

Let's check fig diagnostic...
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled

Let's check your terminal integrations...
✔ Terminal support
✔ Input Method

**Comment by mschrage** [comment]
@tomhendra can you share a screen recording of the behavior? To confirm, the autocomplete window appears with the correct suggestions but it is simply located in the wrong place on the screen?

Does Fig autocomplete work as expected in other terminals, like iTerm or the native terminal app?

**Comment by tomhendra** [comment]
@mschrage the autocomplete window appears on my MBP screen, while the Kitty window I am using is on an external display. I have supplied two separate screen recordings as I can't seem to find a way to record both screens at the same time. 

https://user-images.githubusercontent.com/32566274/208620118-1b48ccb2-6ab7-4be9-83a7-62538db1738d.mp4

It seems that the native terminal and iTerm2 work as expected. 

https://user-images.githubusercontent.com/32566274/208620276-3e8707aa-e771-40d4-9c1b-3745e6cb99ac.mp4

Hope this helps.

**Comment by grant0417** [comment]
That does help, seems that kitty might be reporting the coordinates relative to the local screen, could you try `alacritty` to see if it works in a similar manor? 

@mschrage is this an error with our IME logic or kitty?

**Comment by mschrage** [comment]
This could definitely be an issue with the IME (or how we process the cursor coordinates reported by the IME). If this is the case, it would explain the JetBrains bug reports as well. 

I don't have a monitor that I can use to test this right now, but perhaps @chaynabors can try to reproduce in the office,

**Comment by tomhendra** [comment]
Did you good folks manage to get any further with the Kitty issue? —Sorry to be a pest!

**Comment by grant0417** [comment]
Do you use an external monitor/secondary @tomhendra? That might have been an issue with kitty.

**Comment by tomhendra** [comment]
@grant0417 yes that is exactly the problem I have.

**Comment by grant0417** [comment]
@tomhendra that should be resolved in 2.11 which will be release in a week or two.

**Comment by grant0417** [comment]
2.11 is live, please let me know if this version resolves your issues

**Comment by richardcase** [comment]
Hi @grant0417 - i have upgraded to 2.11 and i'm still encountering the issue with kitty.

**Comment by tomhendra** [comment]
Hello @grant0417, it works on my machine... Thank you!

**Comment by richardcase** [comment]
![ScreenFlow](https://user-images.githubusercontent.com/198425/211609616-9b8019cc-b1c4-4013-b72d-c2d658b829ca.gif)


I ran `fig doctor --verbose`:

```
➜ fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ bash ~/.bashrc integration check
✔ bash ~/.profile integration check
✔ bash ~/.bash_profile integration check
✔ zsh ~/.zshrc integration check
✔ zsh ~/.zprofile integration check

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration
✔ SSH integration

Let's make sure Fig is running...
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
✔ OS is supported
✔ Fish is up to date
✔ Jetbrains Toolbox Check

Let's check fig diagnostic...
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled

Let's check your terminal integrations...
✔ Terminal support
✔ Input Method
```

**Comment by mschrage** [comment]
@richardcase can you run `echo $__CFBundleIdentifier` inside of Kitty and share the output?

Also can you run `fig debug logs` in a separate terminal session and record both terminal windows as you type into kitty?

**Comment by mschrage** [comment]
Hey @richardcase! Glad to hear you're liking Fig :)

Strange request: can you try quitting Microsoft Teams and seeing if this helps?

**Comment by richardcase** [comment]
@mschrage - i quit teams and it still does it.

I will run some tests to confirm, but I think I get the error when I do this:

- Power on my MacBook - which is plugged into an external monitor
- Open the lid to use the keyboard to do the initial login
- Then when fully booted close the lid

And i think it works if i do this:

- Power on my MacBook - which is plugged into an external monitor
- Open the lid to use the keyboard to do the initial login
- immediately shut the lid whilst its still booting (post login)

I will run some tests to see if ^^^^^ is true and confirm back.

**Comment by admapop** [comment]
I'm still encountering this issue with IntelliJ on the latest version.

**Comment by gcstr** [comment]
Fig v2.12.0 and kitty 0.26.5 and the issue is present

**Comment by freddygv** [comment]
Also running into issues with Fig 2.14.2, kitty 0.27.1, and MacOS 12.6.3

If I use the built-in terminal the autocomplete shows up in the correct location, but with kitty it always shows up in the bottom left corner of my external monitor. Even if Kitty is in my laptop's screen.

```
~ 
❯ kitty --version
kitty 0.27.1 created by Kovid Goyal

~ 
❯ echo $__CFBundleIdentifier
net.kovidgoyal.kitty

~ 
❯ fig debug input-method
Installed? true
TISInputSource {
    bundle_id: Some(
        "io.fig.cursor",
    ),
    input_source_id: Some(
        "io.fig.cursor",
    ),
    input_source_category: Some(
        "TISCategoryPaletteInputSource",
    ),
    input_source_is_enabled: Some(
        true,
    ),
    input_source_is_selected: Some(
        true,
    ),
    localized_name: Some(
        "FigInputMethod",
    ),
    input_mode_id: None,
    category_keyboard: None,
}

~ 
❯ fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ bash ~/.bashrc integration check
✔ bash ~/.profile integration check
✔ zsh ~/.zshrc integration check
✔ zsh ~/.zprofile integration check

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration
✔ SSH integration

Let's make sure Fig is running...
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
✔ OS is supported
✔ Fish is up to date
✔ Jetbrains Toolbox Check

Let's check fig diagnostic...
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled

Let's check your terminal integrations...
✔ Terminal support
✔ Input Method
```

**Comment by nanonandi** [comment]
Same as @freddygv for me, always in the bottom left corner 
Fig 2.14.2
Kitty 0.27.1

**Comment by b4lk0n** [comment]
I'm facing the same issue with kitty - autocomplete always appears in the bottom left corner of a display

```bash
> fig --version
fig_cli 2.17.0

> kitty --version
kitty 0.31.0 created by Kovid Goyal

> echo $__CFBundleIdentifier
net.kovidgoyal.kitty

> fig debug input-method
Installed? true
TISInputSource {
    bundle_id: Some(
        "io.fig.cursor",
    ),
    input_source_id: Some(
        "io.fig.cursor",
    ),
    input_source_category: Some(
        "TISCategoryPaletteInputSource",
    ),
    input_source_is_enabled: Some(
        true,
    ),
    input_source_is_selected: Some(
        true,
    ),
    localized_name: Some(
        "FigInputMethod",
    ),
    input_mode_id: None,
    category_keyboard: None,
}
```

**Comment by krissh-the-dev** [comment]
Facing the exact same issue mentioned by @b4lk0n with IntelliJ IDEA.

**Comment by oilcake** [comment]
I still have this issue with all terminal emulators besides iTerm2. MacOS Catalina.

**Comment by carlitos081** [comment]
I have this issue too on mac with Intellij terminal
