### ISSUE TITLE
Autcomplete not working (anymore) on Intellij 2022.3

### ISSUE THREAD

**Issue by imanAzi** [withfig/fig#2120]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

Last Friday autocomplete worked in Intellij Ultimate 2022.3 terminal, today it doesn't. 
I expect to open the terminal in Intellij and that I can use the Fig autocomplete function.

### Actual behaviour

When opening terminal in Intellij, Fig autocomplete doesn't work. When running 'fig doctor', I get the following result:

> ✘ Figterm: Figterm socket write timed out after 1s

> ✘ Doctor found errors. Please fix them and try again.

I have restarted Intellij, 'fig restart', restarted my mac but It still doesn't work and 'fig doctor' keeps giving the same error. 
Autocomplete does work on Iterm2 terminal. 

### Steps to reproduce

1) Open Intellij Ultimate 2022.3 
2) Open terminal in Intellij Ultimate 2022.3
3) type linux commands for autocompletion

### Environment

```yaml
fig-details:
  - 2.8.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - PATH: /Users/iazimnia/go/bin:/opt/homebrew/bin:/usr/local/sbin:/usr/local/bin/brew:/usr/local/bin/:/Users/iazimnia/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/iazimnia/go/bin:/opt/homebrew/bin:/usr/local/sbin:/usr/local/bin/brew:/usr/local/bin/:/Users/iazimnia/.fig/bin:/Users/iazimnia/.local/bin:/Users/iazimnia/Library/Application
    - FIG_PID: 88580
    - FIGTERM_SESSION_ID: a8b54709-1500-431c-b298-30fde9f1bd3c
    - SHELL: /bin/zsh
    - FIG_TERM: 2.8.0
    - FIG_SET_PARENT_CHECK: 1
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.intellij
    - FIG_SET_PARENT: a8b54709-1500-431c-b298-30fde9f1bd3c
    - FIG_HOSTNAME: BEG2N52LV45C
```

**Comment by imanAzi** [comment]
After some troubleshooting, I seem to fixed it:

- Uninstall Fig and reinstall again
- after fresh reinstall ==> 'fig install --input-method'
- Start Intellij

**Comment by grant0417** [comment]
Hey @imanAzi, sorry for the long delay on this but we just released 2.11 which should hopefully resolve these issues!

Let me know if this fixes the issue

**Comment by felixfrey** [comment]
Hey @grant0417, I reinstalled fig and I'm now running 2.11, I still face the same problem as @imanAzi!

**Comment by felixfrey** [comment]
Update: The issue resolved after I restarted my Mac.

**Comment by grant0417** [comment]
@imanAzi, does it work for you now after a restart?
