### ISSUE TITLE
Fig dashboard doesn't load

### ISSUE THREAD

**Issue by boian-ivanov** [withfig/fig#2318]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.2 (21G320)

### Expected behaviour

The Fig dashboard to load and Fig to work across terminals

### Actual behaviour

The Fig dashboard is all white and Fig is not working in any terminals.
I've tried to debug the issue via restarting Fig, killing it, removing credentials from `~/Library/Application Support/fig/` and to reinstall it, but nothing seems to be working.

### Steps to reproduce

Launch Fig 

### Environment

```yaml
fig-details:
  - 2.14.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 12.6.2 (21G320)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/boian.ivanov/Library/Application Support/fig
  - exe-path: /Users/boian.ivanov/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: df2693e8-d935-4e68-8b1f-c4f011274d87
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.0
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Privileges.app/Contents/Resources:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/boian.ivanov/.fig/bin:/Users/boian.ivanov/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 57625
    - FIG_SET_PARENT: df2693e8-d935-4e68-8b1f-c4f011274d87
```

**Comment by boian-ivanov** [comment]
I'm attaching a screenshot here of how it is. No autocompletion is appearing anywhere. The fig CLI is working, but that's about it. Could this be due to an outage? Or is something wrong on my side? 
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/15968453/217553575-d882e4d8-e333-46ec-a519-a4f2d116823e.png">

**Comment by jessewaitz** [comment]
I can confirm that the same exact issue is happening on my machine as well

**Comment by boian-ivanov** [comment]
After running `fig restart` this morning and the auto updater, updating to the latest version, Fig was able to launch the dashboard properly and resolve the above issue. Hopefully this was just a bug with the older version and is now resolved. I'll close this issue for now, but feel free to open it back up if it continues.

**Comment by jessewaitz** [comment]
I ran fig update, fig doctor, and fig restart, and the dashboard will still not load for me. Just a white window, with nothing in it.

**Comment by PedroFarina** [comment]
I can confirm that the exact issue is happening on my machine, and fig restart worked as well

**Comment by melgu** [comment]
I have the same issue. `fig restart` doesn't solve it. `fig doctor` doesn't report any issues.
<img width="1142" alt="White Fig dashboard window with text 'Something went wrong. Error: Missing submessage.'" src="https://github.com/withfig/fig/assets/9601403/1b569dbc-c7b3-466d-9061-0d30d69415b4">

**Comment by malinowskil123** [comment]
☝️ I am having the same issue

**Comment by Dillon-Cox** [comment]
I was having this issue as well, but uninstalled fig and installed code whisperer instead (Fig rebranded as code whisperer). Everything seems to be working fine now, you just run cw to open the dashboard instead of fig.

[https://aws.amazon.com/blogs/devops/introducing-amazon-codewhisperer-for-command-line/]

**Comment by jessewaitz** [comment]
@Dillon-Cox,  I have followed your instructions and It worked for me. thank you.

**Comment by melgu** [comment]
The latest fig version that just released fixed the issue for me. Had to update it through Homebrew (or manually) since the dashboard obviously didn't work.
