### ISSUE TITLE
Support for af-magic theme for oh-my-zsh 

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#311]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Fig is not compatible with the af-magic theme for oh-my-zsh.

### Steps to Reproduce
1. Set the oh-my-zsh theme to af-magic

### Expected Results
Prompt should be unaffected

### Actual Results
The right side prompt looks like it has been shifted left with some extra characters like {% added.

### Environment

```bash
N/A
```

### More Detail

shell::zsh

### Is this issue related to the docs?

- [ ] Yes
- [X] No

**Comment by Loskir** [comment]
I found some sort of a solution
In `~/.fig/fig.sh` comment these lines
```bash
  # We use a shell variable to make sure this doesn't load twice
  #if [[ -z "${FIG_SHELL_VAR}" ]]; then
  #  source ~/.fig/shell/post.sh
  #  FIG_SHELL_VAR=1
  #fi
```
For me it's  lines 23-27

Now both fig works fine and the prompt is unaffected

Note: I'm not sure what issues might occur because of that 😅

**Comment by fwesss** [comment]
I dug through our script and found exactly where the issue is. I just don't know why it's an issue so I don't want to break it just yet 😅

I'll get someone to take a second look so we might be able to fix it.

**Comment by rickdoesburg** [comment]
I'm having the same 'issues'. Everything works fine but I can hardly see where I'm typing :)

**Comment by hossammourad** [comment]
Same issue here.

**Comment by rickdoesburg** [comment]
Awesome! I noticed it right away this morning. Great work, thanks.

**Comment by mcornella** [comment]
@fwesss the change introduces a wokaround for a bug that af-magic had, which ended `$RPS1` with a % character. Now that the bug in Oh My Zsh is fixed, the change you added makes the af-magic not work again: https://github.com/ohmyzsh/ohmyzsh/issues/10517.

Can you remove the workaround?

**Comment by hossammourad** [comment]
The issue is back

![image](https://user-images.githubusercontent.com/4350401/148456945-b78baf3f-68de-4472-8b43-6b1d98d6d6bf.png)

**Comment by hossammourad** [comment]
The issue is back

![image](https://user-images.githubusercontent.com/4350401/148456992-a97b4dce-8245-4c15-a6cf-5913615f92c4.png)

**Comment by hossammourad** [comment]
The issue is back

![image](https://user-images.githubusercontent.com/4350401/148457039-d1e70184-9498-4e73-9374-402b1c458efa.png)
