### ISSUE TITLE
First Install Failed. Rerun install script does nothing 😭 

### ISSUE THREAD

**Issue by ardeora** [withfig/fig#443]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.48 (B264)|/bin/sh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.48 (B264) [U.S.] TRANSLOCATED!!!
UserShell: /bin/sh
Bundle path: /Volumes/fig/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/adeora/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: /Users/adeora/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: false
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

<img width="425" alt="Screen Shot 2021-09-08 at 2 37 53 PM" src="https://user-images.githubusercontent.com/45807386/132566246-609d84a2-3cc8-43c3-9da2-253a28cea2ec.png">

I tried installing fig for the first time and I ran into this problem. Could someone please help me? Thanks in advance!

**Comment by mschrage** [comment]
Hey @ardeora! Try running it one more time - we had some issues with our backend this morning, that should be resolved now!

**Comment by ardeora** [comment]
Thank you so much! That worked 👯  Already loving it. This is a gae changer. Awesome job!

**Comment by VityaSchel** [comment]
> fig diagnostic

I tried reinstalling three times: downloading latest dmg, open it, dragging into applications, open fig from there. still getting "~/.fig is misconfigured"

**Comment by mschrage** [comment]
@VityaSchel try running `fig doctor --verbose`
