### ISSUE TITLE
Suggestion not inserted after pressing Enter in iTerm

### ISSUE THREAD

**Issue by jay-m-z** [withfig/fig#617]
### Description:
When I select a suggestion and press Enter, Fig window disappears but selected suggestion does not get pasted into iTerm window. 

Tested in iTerm 3.4.8 and 3.4.12.
Works in default Terminal App and in VS Code (Insiders build).

According to `fig doctor` iTerm integration is enabled but VS Code extension is missing (but it works in VS Code and not in iTerm?).

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.52 (B317)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B317) [Polish - Pro] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/[REDACTED]/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/[REDACTED]/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @jay-m-z! Sorry to hear you're running into issues. Does this happen consistently or was it a one-off occurrence?

Have you customized your iTerm Profile at all? (eg. like launching multiple panes/tabs simultaneously?)

**Comment by jay-m-z** [comment]
It happens constantly and yes, I'm running two panes as default.
I tried opening a single pane new window and it works there, even after splitting it into two panes.

**Comment by mschrage** [comment]
Okay this is a known issue that I am planning on fixing this week.

Question: how do you configure iTerm to open two panes automatically? I will do my best to make sure your workflow is supported :)

**Comment by jay-m-z** [comment]
Open a new window -> right-click on it -> Split Pane Vertically/Horizonally.
Then in menu bar click Window -> Save Window Arrangement and save it. Go to Preferences -> Arrangements tab and set the new arrangement as default.

**Comment by hu13** [comment]
I am also running into this issues and it happens consistently on both iterms and vscode terminal on apple m1 macbook.
I am not running two panes automatically.

```
❯ fig diagnostic
Fig Version: Version 1.0.52 (B317) [British]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path:
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (19223) - ttys004
Current working directory: /Users/hangkun
Current window identifier: 400/C5A7C232-EA9F-4A0D-8A48-FC0A1F063C7B% (com.googlecode.iterm2)

**Comment by hu13** [comment]
I just figured it out from the other issue after running `fig doctor`:

```
Fig ENV variables need to be at the very beginning and end of ~/.zshrc
If you see the FIG ENV VARs in ~/.zshrc, make sure they're at the very beginning (pre) and end (post). Open a new terminal then rerun the the doctor.
If you don't see the FIG ENV VARs in ~/.zshrc, run 'fig app install' to add them. Open a new terminal then rerun the doctor.

**Comment by mschrage** [comment]
Hey @jay-m-z! I've pushed a fix that I think should resolve this issue.

You can update to the latest version by running `fig update` or you can re-download the app [here](https://fig.io/welcome)!

**Comment by jay-m-z** [comment]
Hi! Do you mean version 1.0.52 (B326)? If so I'm sorry to say it did not change anything for me. 
fig still does not insert suggestions into two-pane windows opened by default and I need to manually restore window layout after starting iTerm (Shift+Cmd+R).

**Comment by mschrage** [comment]
Oof. I'm sorry to hear that @jay-m-z. First, make sure you're on `B328` or higher. If you're still running into issues on the newest version, we should jump on a debugging call together: https://calendly.com/mschrage/30min

I really want to get this fixed for you!

**Comment by iWECon** [comment]
@mschrage 

I have the same problem, and I don't think the problem is iTerm2.
This problem can be solved after restarting the mac.

This problem reappears: lock the screen after starting the computer, then enter the password and then enter the desktop, this problem will appear until it restarts again.

![CleanShot 2021-12-18 at 23 26 37](https://user-images.githubusercontent.com/16604027/146648089-5f275251-01bf-41a3-a4e1-56a80b8e9e15.gif)

**Comment by mschrage** [comment]
Hey @iWECon! Thanks for adding instructions on how to reproduce. It seems like the communication between the macOS app and your terminal session breaks after the computer screen is locked. (I have been unable to reproduce this)

My assumption is that this is localized to any sessions created prior to locking your screen? If you open a new terminal session once you've unlocked your computer, does it also have this issue?

**Comment by iWECon** [comment]
> Hey @iWECon! Thanks for adding instructions on how to reproduce. It seems like the communication between the macOS app and your terminal session breaks after the computer screen is locked. (I have been unable to reproduce this)
> 
> My assumption is that this is localized to any sessions created prior to locking your screen? If you open a new terminal session once you've unlocked your computer, does it also have this issue?

You are right, open a new terminal session is normal~

**Comment by mschrage** [comment]
In the broken terminal, can you run `export FIG_LOG_LEVEL=DEBUG` and then in a separate session run `fig debug logs`.

Then can you record your screen, typing into the broken terminal session and inserting text?

**Comment by mschrage** [comment]
Hey @iWECon! Are you free to debug this over a call? https://calendly.com/mschrage/30min

**Comment by iWECon** [comment]
@mschrage Sorry, I just saw.
I can use it normally now, and I just reset configuration of iterm~
Thank you for your reply. If similar problems occur later, I will contact you again.

**Comment by mschrage** [comment]
@iWECon do you remember what iTerm configuration you had changed?

**Comment by iWECon** [comment]
@mschrage I can't be sure, but I can upload my profile configure.
```shell
> unzip iTerm2-Profiles-Person.json.zip
> cp Person.json ~/Library/Application Support/iTerm2/DynamicProfies/
```

[iTerm2-Profiles-Person.json.zip](https://github.com/withfig/fig/files/7791250/iTerm2-Profiles-Person.json.zip)

**Comment by AlexVipond** [comment]
Confirming that I also solved this problem recently by updating Fig. Not sure what Fig version I was on before, but I was already on the latest iTerm2, and I updated to Fig 1.0.57. Still had to restart iTerm, but after that, it was fixed.

**Comment by mschrage** [comment]
@AlexVipond can you run `fig diagnostic` and share the output here?

**Comment by AlexVipond** [comment]
```
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 203
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro14,1
  - Chip:
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 10.14.6 (18G9323)
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /Users/Alex/Packages/baleada/vue-features
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 5330/% (com.googlecode.iterm2)
  - Active Process: bash (69095) - /dev/ttys003
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=w0t1p0:1BCB56CD-4CF2-478E-A405-63C1DD14BBA9
    - PATH=/Users/Alex/.nvm/versions/node/v17.2.0/bin:/Users/Alex/.rbenv/shims:/usr/local/sbin:/usr/local/opt/qt/bin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Users/Alex/.fig/bin:/Users/Alex/.local/bin:/Users/Alex/.composer/vendor/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.4.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by nkehoe03** [comment]
> @iWECon do you remember what iTerm configuration you had changed?

This issue should not be closed imo as I got it for the first time yesterday.

**Comment by potts99** [comment]
I also have this issue

**Comment by MichaelToLearn** [comment]
Same here. I could only make it continue to confirm the list by clicking the item.

**Comment by wmonecke** [comment]
Updated iTerm today and started getting this issue now...

**Comment by KarmaBlackshaw** [comment]
> Updated iTerm today and started getting this issue now...
> 
> Edit: Managed to make it work again by opening Activity Monitor -> Look for "fig" -> Force kill it -> Restart iTerm.

This hack worked like a charm, though I am not sure as to why this happens

**Comment by carlosbensant** [comment]
To make it work back to normal I usually run `fig restart`.

This is happening to me more frequently, it never used to happen. I thought it was my fig version but I have the latest version installed.
