### ISSUE TITLE
cwd is not updated in tmux

### ISSUE THREAD

**Issue by dnjp** [withfig/fig#618]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When using Fig in iTerm or MacOS Terminal everything works properly. However, when starting tmux with the following `.tmux.conf` the `cwd` for fig is not updated so commands like `cd` only reports completion candidates for files/directories in the directory that tmux was started. Here's my configuration:

.tmux.conf:
```
# Fig Tmux Integration: Enabled
source-file ~/.fig/tmux
# End of Fig Tmux Integration
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B317)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B317) [Colemak] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/daniel/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/daniel/.nvm/versions/node/v14.18.0/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/daniel/go/bin:/usr/local/go/bin:/opt/homebrew/opt/llvm/bin:/opt/homebrew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/daniel/.cargo/bin:/Users/daniel/.fig/bin:/Users/daniel/google-cloud-sdk/bin:/opt/homebrew/sbin:/opt/homebrew/opt/llvm/bin:/bin:/usr/bin:/usr/local/bin:/Users/daniel/work/martin-bidder/bin:/Users/daniel/.local/bin:/usr/local/share/cqlsh/cqlsh-5.1.20/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /opt/homebrew/Cellar/tmux/3.2a/bin/tmux (24182) - /dev/ttys003
Current working directory: /Users/daniel
Current window identifier: 8954/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Running `fig source` should fix this issue in any given terminal session, but this is definitely a bug with our tmux integration. Thanks for reporting it @dnjp.

**Comment by dnjp** [comment]
@mschrage Thanks for your response. I tried both `fig source` and `fig app set-path` and neither resolved the issue. Can you think of a possible workaround for this issue while a more robust solution is being worked on?

**Comment by mschrage** [comment]
How do you launch into `tmux`? Out of curiosity, what happens if you prefix the command with `FIG_NEW_SESSION=1`?

eg. something like `FIG_NEW_SESSION=1 tmux`

**Comment by dnjp** [comment]
No dice, unfortunately. It was worth a shot 🤷‍♂️
![Screen Shot 2021-11-22 at 2 51 48 PM](https://user-images.githubusercontent.com/37786372/142926026-da920e0d-53df-414c-a730-3c6ce7fe3a1b.png)

**Comment by mschrage** [comment]
Thanks for testing it for me. We are switching out how we determine which terminal session is active and I think that may resolve the issue for you. Stay tuned for the next release.

**Comment by dnjp** [comment]
![Screen Shot 2021-12-06 at 12 32 39 PM](https://user-images.githubusercontent.com/37786372/144893770-25fadbe6-29f0-43db-b619-49ebe46d9b15.png)

I'm updated Fig to the latest release and so far it looks like this issue is still present. I tried this with `FIG_NEW_SESSION=1 tmux` as well and in both cases cwd is not updated.

**Comment by dnjp** [comment]
![Screen Shot 2021-12-16 at 2 26 18 PM](https://user-images.githubusercontent.com/37786372/146435747-3a21028c-f129-41b5-a462-11e5a69e2564.png)

As far as I can tell, this issue has been resolved with recent updates. Completion is now working in tmux both with and without splits!

**Comment by mschrage** [comment]
Hey @dnjp! I'm glad to hear everything is working for you. 

Heads up that`tmux` still isn't _officially_ supported since there are lots edge cases we probably haven't accounted for.
