### ISSUE TITLE
Not working in iterm

### ISSUE THREAD

**Issue by xedef** [withfig/fig#863]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig is working correctly in both Apple and VSCode terminals but not in iTerm. Autocompletion is not shown for any command.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [Dev] [Canadian English] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/fede/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/Caskroom/miniconda/base/bin:/opt/homebrew/Caskroom/miniconda/base/condabin:/Users/fede/.nvm/versions/node/v16.13.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/fede/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (65026) - /dev/ttys006
Current window identifier: 208/% (com.googlecode.iterm2)
Path: /opt/homebrew/Caskroom/miniconda/base/bin:/opt/homebrew/Caskroom/miniconda/base/condabin:/Users/fede/.nvm/versions/node/v16.13.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/fede/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t1p0:5FA1186E-6839-4A3A-9002-411E012775B1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
We've made a lot of improvements recently, should be working fine now. If it's not, let us know and we'll reopen!

**Comment by xedef** [comment]
Still not working. I tried to reinstall it with no success, diagnostic doesn't say anything is wrong, fig doctor is kinda erratic and it doesn't say anything is wrong.
Is there any place were I can check for a detailed log on why is failing for iterm?
